### it has to pick values from task level
- name: variables from task level
  hosts: localhost
  vars: 
    Course: "DevOps"
    Trainer: "Siva"
    Duration: "110hrs"
  tasks:
  - name: check variables
    vars: # task level
      Course: "DevOps with AWS"
      Trainer: "surya"
    ansible.builtin.debug:
      msg: "HI im learning {{Course}}, Trainer is {{Trainer}}, Duration is {{110hrs}}"